package com.zivkesten.test.data

data class CaughtException(
    val exception: String,
    val timeStamp: Long,
)




